plugins {
    alias libs.plugins.fabricLoom apply(false)
    alias libs.plugins.modDevGradle apply(false)
    alias libs.plugins.curseForgeGradle apply(false)
    alias libs.plugins.modrinthMinotaur apply(false)
}

tasks.register("buildAll") {
    group = "dev"
    description = "Build Fabric + NeoForge + Polymer jars"
    dependsOn(":fabric:jar", ":neoforge:jar", ":polymer:jar")
}
tasks.register("datagen") {
    group = "dev"
    description = "Run Fabric data generation"
    dependsOn(":fabric:runData")
}
tasks.register("runClientFabric") {
    group = "dev"
    description = "Run Fabric Minecraft Client"
    dependsOn(":fabric:runClient")
}
tasks.register("runClientNeoforge") {
    group = "dev"
    description = "Run NeoForge Minecraft Client"
    dependsOn(":neoforge:runClient")
}
tasks.register("runServerNeoforge") {
    group = "dev"
    description = "Run Fabric Minecraft Client"
    dependsOn(":fabric:runServer")
}
tasks.register("runServerFabric") {
    group = "dev"
    description = "Run NeoForge Minecraft Client"
    dependsOn(":neoforge:runServer")
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'java-library'

    configurations.configureEach {
        resolutionStrategy {
            cacheChangingModulesFor 60, 'seconds'
            cacheDynamicVersionsFor 60, 'seconds'
        }
    }

    plugins.withType(JavaPlugin).tap {
        configureEach {
            dependencies {
                implementation('com.squareup.okhttp3:okhttp:4.12.0')
                implementation('com.squareup.okio:okio:3.4.0')
                //noinspection DifferentStdlibGradleVersion
                implementation('org.jetbrains.kotlin:kotlin-stdlib:1.9.10')
                implementation('org.jetbrains.kotlin:kotlin-stdlib-common:1.9.10')
                implementation('org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.10')
                implementation('org.reflections:reflections:0.10.2')

                compileOnly 'org.projectlombok:lombok:1.18.40'
                annotationProcessor 'org.projectlombok:lombok:1.18.40'

                compileOnly 'com.google.auto.value:auto-value:1.10.4'
                annotationProcessor 'com.google.auto.value:auto-value:1.10.4'

                compileOnly 'io.soabase.record-builder:record-builder-core:39'
                annotationProcessor 'io.soabase.record-builder:record-builder-processor:39'
            }
        }
        java {
            toolchain {
                languageVersion = JavaLanguageVersion.of(25)
            }
        }
    }
    tasks.withType(JavaCompile).configureEach {
        options.compilerArgs += ["-Xlint:-removal", "-Xlint:-dep-ann"]
    }
}
