# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.7
yarn_mappings=1.21.7+build.1
loader_version=0.16.14

# Mod Properties
mod_version=0.3.6
maven_group=cc.thonly.reverie_dreams
archives_base_name=reverie_dreams

# Dependencies
fabric_version=0.128.2+1.21.7
polymer_version=0.13.8+1.21.8
factorytools_version=0.7.4+1.21.8
sgui_version=1.10.1+1.21.7
midnightlib_version=1.7.5+1.21.6-fabric
fabric_permissions_api=0.4.0
bil_version=1.5.0+1.21.6
mapcanvas_version=0.5.1+1.21.5
modmenu_version=15.0.0-beta.3

# MCRes
loom_resources_base=https://bmclapi2.bangbang93.com/assets/
loom_version_manifests=https://bmclapi2.bangbang93.com/mc/game/version_manifest.json
loom_experimental_versions=https://maven.fabricmc.net/net/minecraft/experimental_versions.json

#systemProp.java.net.socks.host=127.0.0.1
#systemProp.java.net.socks.port=10808
