# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.18.4
loom_version=1.14-SNAPSHOT

# Mod Properties
mod_version=0.4.14
maven_group=cc.thonly.reverie_dreams
archives_base_name=reverie_dreams

# Dependencies
fabric_api_version=0.141.1+1.21.11
polymer_version=0.15.1+1.21.11
factorytools_version=0.9.3+1.21.11
sgui_version=1.12.0+1.21.11
midnightlib_version=1.9.2+1.21.11-fabric
molang_compiler_version=3.1.1.19
fabric_permissions_api=0.6.1
bil_version=2.0.2+1.21.11
mapcanvas_version=0.7.0+1.21.11
camera_obscura=1.2.2+1.21.11
modmenu_version=17.0.0-beta.2
server_translations_api_version=2.5.2+1.21.9-pre3

# MCRes
#loom_resources_base=https://bmclapi2.bangbang93.com/assets/
#loom_version_manifests=https://bmclapi2.bangbang93.com/mc/game/version_manifest.json
#loom_experimental_versions=https://maven.fabricmc.net/net/minecraft/experimental_versions.json

#systemProp.java.net.socks.host=127.0.0.1
#systemProp.java.net.socks.port=10808
