# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.16.14

# Mod Properties
mod_version=0.4.9
maven_group=cc.thonly.reverie_dreams
archives_base_name=reverie_dreams

# Dependencies
fabric_version=0.119.4+1.21.4
polymer_version=0.11.8+1.21.4
factorytools_version=0.5.0+1.21.4
sgui_version=1.8.2+1.21.4
midnightlib_version=1.9.2+1.21.5-fabric
fabric_permissions_api=0.3.3
bil_version=1.2.2+1.21.4
mapcanvas_version=0.5.0+1.21.3
camera_obscura=1.2.0+1.21.4
modmenu_version=13.0.3

# MCRes
#loom_resources_base=https://bmclapi2.bangbang93.com/assets/
#loom_version_manifests=https://bmclapi2.bangbang93.com/mc/game/version_manifest.json
#loom_experimental_versions=https://maven.fabricmc.net/net/minecraft/experimental_versions.json

#systemProp.java.net.socks.host=127.0.0.1
#systemProp.java.net.socks.port=10808
