package cc.thonly.reverie_dreams.neoforge.compat.neo_mystia_izakaya;

import cc.thonly.reverie_dreams.ReverieDreams;
import cc.thonly.reverie_dreams.util.item.ReverieDreamsConsts;
import cc.thonly.reverie_dreams.util.item.NeoMystiasIzakayaConsts;
import lombok.extern.slf4j.Slf4j;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.Identifier;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.fml.ModContainer;
import net.neoforged.fml.common.Mod;
import net.neoforged.fml.loading.FMLLoader;
import net.neoforged.neoforge.registries.DeferredRegister;

import java.util.Objects;

@Slf4j
@SuppressWarnings({"unused"})
@Mod(value = ReverieDreams.MOD_ID)
public class NeoMystiasIzakayaCompat {
    public static final DeferredRegister.Items ITEMS = DeferredRegister.createItems(ReverieDreams.MOD_ID);
    public static final DeferredRegister.Blocks BLOCKS = DeferredRegister.createBlocks(ReverieDreams.MOD_ID);
    public static final DeferredRegister<BlockEntityType<?>> BLOCK_ENTITY_TYPES = DeferredRegister.create(Registries.BLOCK_ENTITY_TYPE, ReverieDreams.MOD_ID);

    public NeoMystiasIzakayaCompat(IEventBus modEventBus, ModContainer modContainer) {
        if (FMLLoader.getCurrent().getLoadingModList().getMods().stream().noneMatch(e-> Objects.equals(e.getModId(), "neo_mystias_izakaya"))) {
            ITEMS.register(modEventBus);
            BLOCKS.register(modEventBus);
            BLOCK_ENTITY_TYPES.register(modEventBus);
        }
    }

    static {
        BLOCKS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "boiling_pot"), Identifier.fromNamespaceAndPath("reverie_dreams", "cooking_pot"));
        BLOCKS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "grill"), Identifier.fromNamespaceAndPath("reverie_dreams", "grill"));
        BLOCKS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "frying_pan"), Identifier.fromNamespaceAndPath("reverie_dreams", "frying_pan"));
        BLOCKS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "steamer"), Identifier.fromNamespaceAndPath("reverie_dreams", "steamer"));
        BLOCKS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cutting_board"), Identifier.fromNamespaceAndPath("reverie_dreams", "cutting_board"));

        BLOCK_ENTITY_TYPES.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "boiling_pot"), Identifier.fromNamespaceAndPath("reverie_dreams", "kitchen_block"));
        BLOCK_ENTITY_TYPES.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "grill"), Identifier.fromNamespaceAndPath("reverie_dreams", "kitchen_block"));
        BLOCK_ENTITY_TYPES.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "frying_pan"), Identifier.fromNamespaceAndPath("reverie_dreams", "kitchen_block"));
        BLOCK_ENTITY_TYPES.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "steamer"), Identifier.fromNamespaceAndPath("reverie_dreams", "kitchen_block"));
        BLOCK_ENTITY_TYPES.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cutting_board"), Identifier.fromNamespaceAndPath("reverie_dreams", "kitchen_block"));

        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/bamboo_shoot"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/bamboo_shoots"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/bingdi_lotus"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/twin_lotus"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/black_salt"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/black_salt"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/boar_meat"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/wild_boar_meat"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/broccoli"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/broccoli"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/butter"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/butter"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/cheese"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/cheese"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/chestnut"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/chestnut"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/chili"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/chili"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/cicada_slough"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/cicada_shell"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/crab"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/crab"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/cream"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/cream"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/creeping_fig"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/ficus_microcarpa"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/cucumber"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/cucumber"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/dew"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/dew"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/flour"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/flour"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/flower"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/flowers"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/ginkgo_nut"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/ginkgo"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/grapes"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/grape"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/iberico_pork"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/black_pork"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/jiguru_berry"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/puff_yo_fruit"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/lamprey"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/hagfish"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/lemon"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/lemon"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/lotus_seed"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/lotus_nuts"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/lunar_herb"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/moonflower"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/octopus"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/octopus"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/onion"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/onion"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/peach"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/peach"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/pine_nut"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/pine_nut"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/plum"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/plum"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/premium_tuna"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/supreme_tuna"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/radish"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/white_radish"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/red_bean"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/red_beans"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/red_toon"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/toon"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/salmon"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/salmon"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/sea_urchin"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/sea_urchin"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/shrimp"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/shrimp"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/snow_fungus"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/tremella"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/sticky_rice"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/sticky_rice"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/strong_capsaicin"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/capsaicin"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/sweet_potato"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/sweet_potato"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/tofu"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/tofu"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/tomato"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/tomato"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/trout"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/trout"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/truffle"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/truffle"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/tuna"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/tuna"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/udumbara"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/udumbara"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/venison"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/venison"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "ingredient/wagyu_beef"), Identifier.fromNamespaceAndPath("reverie_dreams", "ingredient/wagyu_beef"));

        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/affogato"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/affgado"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/zun_beer"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/beer"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/giant_popsicle"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/big_popsicle"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/wind_priestess"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/blessing_wind"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/coffee"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/coffee"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/daiginjo"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/daiginjo"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/daughter_of_the_sea"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/daughter_of_the_sea"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/akatsuki"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/dawn"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/makai_coffee"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/demonic_coffee"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/oni_killer"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/demon_slayer"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/drunken_bard"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/drunk_actor"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/fairy_dew"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/fairy_rain"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/fire_rats_robe"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/fire_rat_fur"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/full_moons_eve"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/fourteenth_night"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/fruity_highball"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/fruity_high_ball"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/fruity_sour"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/fruity_sour"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/godfather"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/godfather"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/divine_wheat"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/gods_wheat"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/green_tea"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/green_tea"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/jade_dew_tea"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/gyokuro_tea"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/this_side_up"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/heaven_and_earth_are_useless"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/iceberg_kedama_lemonade"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/iceberg_maple_frozen_lemon"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/komeiji_ice_cream"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/komeiji_ice_cream"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/mango_pomelo_sago"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/mango_pomelo_sago"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/milk"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/milk"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/mojito_sphere"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/mojito_burst_ball"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/moon_rocket"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/moon_rocket"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/negroni"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/negroni"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/ordinary_fitness_tea"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/ordinary_fitness_tea"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/dassai"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/otter_festival"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/ice_cream_smoothie"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/paleo_creamy_smoothie"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/umeshu"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/plum_wine"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/mio"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/qi"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/qilin"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/qilin"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/ribovitan"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/qi_health"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/grapefruit_juice"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/red_grapefruit_juice"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/scarlet_mist"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/red_mist"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/satellite_ice_coffee"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/satellite_iced_coffee"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/bloody_remy"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/scarlet_devil"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/scarlet_tea"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/scarlet_devil_mansion_black_tea"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/ramune"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/soda"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/space_beer"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/space_beer"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/sparrow_sake"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/sparrow_sake"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/sangetsusei"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/sun_moon_star"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/tengu_tango"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/tengu_dance"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "beverages/cassia_wine"), Identifier.fromNamespaceAndPath("reverie_dreams", "drink/winter_brew"));

        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/all_meat_feast"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/all_meat_feast"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/peach_shrimp_salad"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/arctic_sweet_shrimp_and_peach_salad"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/tempura_platter"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/assorted_tempura"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/little_sweet_poison"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/a_little_sweet_poison"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/creamy_crab"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/baked_crab_with_cream"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/baked_sweet_potato"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/baked_sweet_potatoes"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/pork_bamboo_shoots_stir_fry"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/bamboo_shoots_fried_meat"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/bamboo_meat_pot"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/bamboo_shoots_stewed_in_stone_pot"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/steamed_egg_bamboo_shoots"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/bamboo_steamed_egg"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/drunk_shrimp_in_bamboo"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/bamboo_tube_roasted_drunken_shrimp"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/rice_powder_meat"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/bamboo_tube_steamed_pork"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/imitation_bear_paw"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/bear_paw"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/two_flavor_beef_hotpot"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/beef_hot_pot"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/beef_bowl"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/beef_rice"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/beef_wellington"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/beef_wellington"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/kabuto_steamed_cake"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/beetle_steamed_cake"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/biscay_biscuits"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/biscay_biscuits"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/sichuan_boiled_fish"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/boiled_fish"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/kabayaki_lampreys"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/braised_eel"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/peach_braised_pork"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/braised_pork_with_peach"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/burn_out_pudding"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/burnt_pudding"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/classic_steak"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/butter_steak"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/honeyed_chestnut"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/candied_chestnuts"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/candied_sweet_potato"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/candied_sweet_potato"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/kittens_water_play"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/cats_playing_in_water"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/neko_manma"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/cat_food"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/kitten_canele"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/cat_kululi"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/kitten_pizza"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/cat_pizza"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/cheese_omelette"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/cheese_egg"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/carved_rose_salad"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/cold_dish_carving"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/fresh_tofu"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/cold_tofu"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/rainbow_pan_fried_pork_buns"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/colorful_jade_fried_buns"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/boiled_tofu"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/cooking_tofu"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/creamy_vegetable_chowder"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/cream_stew"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/crispy_spirals"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/crisp_cyclone"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/dark_matter"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/dark_cuisine"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/fried_cicada_sloughs"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/deep_fried_cicada_shells"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/misery_cheese_sticks"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/depressed_cheese_sticks"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/dew_runny_eggs"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/dew_boiled_eggs"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/dorayaki"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/dorayaki"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/dumplings"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/dumpling"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/eel_bowl_with_egg"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/eel_egg_donburi"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/eggs_benedict"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/eggs_benedict"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/energy_skewer"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/energy_string"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/falling_blossoms"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/failing_sakura_snow"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/scrumptious_storm"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/fantasy_is_all_the_rage"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/dragon_carp"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/fish_leaps_over_dragon_gate"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/natures_beauty"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/flowers_birds_wind_and_moon"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/flowing_somen"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/flowing_water_noodles"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/fried_lampreys"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/fried_hagfish"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/fried_pork_cutlet"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/fried_pork_cutlet"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/pork_stir_fry"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/fried_pork_shreds"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/deep_fried_shrimp_tempura"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/fried_shrimp_tempura"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/deep_fried_tofu"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/fried_tofu"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/tomato_fries"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/fried_tomato_strips"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/heart_throbbing_surprise"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/fright_adventure"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/hunters_casserole"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/game_soup"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/buddha_jumps_over_the_wall"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/gensokyo_buddha_jumps_over_the_wall"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/star_lotus_ship"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/gensokyo_star_lotus_ship"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/giant_tamagoyaki"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/giant_tamagoyaki"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/golden_ribs_soup"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/ginkgo_and_radish_pork_rib_soup"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/gloomy_fruit_pie"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/gloomy_fruit_pie"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/tangyuan"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/glutinous_rice_balls"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/golden_crispy_fish_cakes"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/golden_crispy_fish_cake"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/daimyos_feast"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/grand_banquet"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/bamboo_spring"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/green_bamboo_welcomes_spring"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/mushroom_herb_road"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/green_fairy_mushroom"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/grilled_lamprey"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/grilled_hagfish"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/pork_rice_ball"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/grilled_pork_rice_balls"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/heart_warming_congee"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/heart_porridge_gruel"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/caution_hellish_spice"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/hell_thrill_warning"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/pure_white_lotus"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/holy_white_lotus_seed_cake"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/cantonese_char_siu"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/honey_bbq_pork"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/hourai_branch"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/horai-dama_no_eda"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/pancakes_with_syrup"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/hot_waffles"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/hot_pepper_soup"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/hula_soup"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/lions_head"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/lion_head"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/dragonsong_peach"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/longyin_peach"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/ceiling_longing_pie"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/looking_up_at_the_ceiling_fruit_pie"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/lotus_fish_lamps"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/lotus_fish_rice_bowl"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/buddhas_delight"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/luohan_vegetarian"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/mad_hatters_tea_party"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/mad_hatter_tea_party"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/fujis_lava"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/magma"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/cubic_kedama_volcanic_tofu"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/maoyu_lava_tofu"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/cubic_kedama_ice_cream"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/maoyu_tricolor_ice_cream"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/mapo_tofu"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/mapo_tofu"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/cream_of_mushroom_soup"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/milky_mushroom_soup"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/mochi"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/mochi"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/molecular_egg"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/molecular_egg"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/lunar_dango"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/moonlight_dumplings"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/moonlight_over_the_lotus_pond"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/moonlight_over_lotus_pond"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/moon_cake"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/moon_cake"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/lunar_lover_biscuits"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/moon_lovers"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/mushroom_maidens_tip_tap_pot"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/mushroom_girls_dance_stew"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/pork_mushroom_stir_fry"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/mushroom_meat_slices"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/nigiri_sushi"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/nigiri_sushi"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/oedo_boat_feast"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/oedo_boat_festival"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/okonomiyaki"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/okonomiyaki"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/instantdeath"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/one_hit_kill"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/ordinary_eat_me_cupcake"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/ordinary_small_cake"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/golden_two_shroom_wrap"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/pan_fried_mushroom_meat_roll"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/salmon_steak"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/pan_fried_salmon"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/peach_flower_crystal_roll"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/peach_blossom_glaze_roll"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/peach_tapioca"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/peach_blossom_soup"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/immortal_turkey"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/phoenix"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/pickles"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/pickled_cucumbers"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/ino_shika_chou"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/pig_deer_butterfly"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/pine_nut_cake"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/pine_nut_cake"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/smoked_buccaneer"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/pirate_bacon"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/plum_tea_rice"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/plum_tea_rice"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/scholars_ginkgo"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/poetry_and_ginkgo"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/miasma_garden"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/poisonous_garden"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/pork_trout_kebab"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/pork_and_trout_smoked"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/pork_bowl"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/pork_rice"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/potato_croquettes"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/potato_croquettes"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/imitation_shirikodama"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/pseudo_jiritama"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/shrimp_stuffed_pumpkin"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/pumpkin_shrimp_cake"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/long_hair_princess"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/rapunzel"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/real_seafood_miso_soup"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/real_seafood_miso_soup"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/red_bean_daifuku"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/red_bean_daifuku"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/energy_pudding"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/refreshing_pudding"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/against_the_world"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/reversing_the_world"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/rice_ball"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/rice_ball"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/italian_risotto"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/risotto"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/roasted_mushroom"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/roasted_mushrooms"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/sakura_pudding"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/sakura_pudding"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/salmon_tempura"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/salmon_tempura"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/sashimi_platter"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/sashimi_platter"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/scarlet_devil_cake"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/scarlet_devils_cake"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/scone"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/scones"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/agony_oden"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/screaming_oden"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/seafood_miso_soup"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/seafood_miso_soup"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/sea_urchin_sashimi"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/sea_urchin_sashimi"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/urchin_raindrop_cake"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/sea_urchin_shingen_pancake"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/secret_dried_fish_crisps"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/secret_dried_fish"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/secret_savory_mushroom_hotpot"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/secret_mushroom_casserole"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/seven_colored_yokan"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/seven_colored_yokan"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/white_deer_unyielding_pine"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/shiraga_sadamatsu"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/yashouma_dango"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/skinny_horse_dumpling"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/shirayuki"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/snow_white"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/urchin_steamed_egg"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/steamed_egg_with_sea_urchin"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/stinky_tofu"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/stinky_tofu"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/power_soup"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/strength_soup"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/supreme_seafood_noodles"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/superme_seafood_noodles"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/eight_trigram_fish_maws"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/taichi_bagua_fish_maw"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/kaguya_hime"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/taketorihime"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/takoyaki"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/takoyaki"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/palace_of_the_han"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/the_beauty_of_han_palace"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/faint_dream"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/the_dream"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/planet_mars"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/the_mars"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/origin_of_life"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/the_source_of_life"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/tianshis_stewed_mushrooms"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/tianshi_braised_chestnut_mushrooms"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/miso_tofu"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/tofu_miso"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/tofu_stew"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/tofu_pot"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/tonkotsu_ramen"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/tonkotsu_ramen"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/toon_pancake"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/toon_pancakes"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/niten_ichiryu"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/two_heavens_one_style"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/udumbara_cake"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/udumbara_cake"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/unconscious_youkai_mousse"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/unconscious_monster_mousse"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/vegetable_salad"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/vegetable_special"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/pink_rice_ball"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/warm_rice_ball"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/peach_yatsuhashi"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/white_peach_eight_bridge"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/unzan_cotton_candy"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/yunshan_cotton_candy"));
        ITEMS.addAlias(Identifier.fromNamespaceAndPath("neo_mystias_izakaya", "cuisines/hodgepodge"), Identifier.fromNamespaceAndPath("reverie_dreams", "food/zhaji"));
    }
}