plugins {
    id 'multiloader-common'
    alias libs.plugins.modDevGradle
}

neoForge {
    neoFormVersion = "1.21.11-20251209.172050"
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = minecraft_version
        mappingsVersion = parchment_mapping_version
    }
}

dependencies {
    compileOnly("org.spongepowered:mixin:${mixin_version}")
}

apply from: rootProject.file('repositories.gradle')
dependencies {
    implementation("net.blay09.mods:balm-common:${balm_version}") {
        changing = balm_version.endsWith("SNAPSHOT")
    }
    implementation("gg.moonflower:molang-compiler:3.1.1.19")
    implementation("software.bernie.geckolib:geckolib-common-${minecraft_version}:${geckolib_version}")
//    implementation("dev.architectury:architectury:${architectury_api_version}")
    compileOnly("cc.cassian.rrv:reliable-recipe-viewer-neoforge:${rrv_version}+${minecraft_version}")

    api("cc.thonly:sgui_balm-common:1.21.11-21.11.0")
    api("cc.thonly:keine-common:${keine_api_version}")
    compileOnly("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
    runtimeOnly("mezz.jei:jei-${minecraft_version}-common:${jei_version}")
    compileOnly("me.shedaniel:RoughlyEnoughItems-neoforge:${rei_version}")

//    compileOnly("me.shedaniel:RoughlyEnoughItems-api:${rei_version}")
//    compileOnly("me.shedaniel:RoughlyEnoughItems-default-plugin:${rei_version}")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.18.3")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.18.3")
}


configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
    commonGeneratedResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

sourceSets {
    generated {
        resources {
            srcDir 'src/generated/resources'
        }
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
    commonGeneratedResources sourceSets.generated.resources.sourceDirectories.singleFile
}
