plugins {
    id 'multiloader-common'
    alias libs.plugins.modDevGradle
}

neoForge {
    neoFormVersion = "26.1.2-1"
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
}

dependencies {
    compileOnly("org.spongepowered:mixin:${mixin_version}")
}

apply from: rootProject.file('repositories.gradle')
dependencies {
    implementation("net.blay09.mods:balm-common:${balm_version}") {
        changing = balm_version.endsWith("SNAPSHOT")
    }
    implementation("gg.moonflower:molang-compiler:3.1.1.19")
    implementation("com.geckolib:geckolib-common-${minecraft_version}:${geckolib_version}")

    api("cc.thonly:sgui-common:${sgui_forgelike_version}")
    api("cc.thonly:keine-common:${keine_version}")
    compileOnly("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
    runtimeOnly("mezz.jei:jei-${minecraft_version}-common:${jei_version}")
//    compileOnly("me.shedaniel:RoughlyEnoughItems-neoforge:${rei_version}")

//    compileOnly("me.shedaniel:RoughlyEnoughItems-api:${rei_version}")
//    compileOnly("me.shedaniel:RoughlyEnoughItems-default-plugin:${rei_version}")
}


configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
    commonGeneratedResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

sourceSets {
    generated {
        resources {
            srcDir 'src/generated/resources'
        }
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
    commonGeneratedResources sourceSets.generated.resources.sourceDirectories.singleFile
}
