package cc.thonly.reverie_dreams.registry.content.item;

import cc.thonly.reverie_dreams.registry.content.component.RDDataComponents;
import net.blay09.mods.balm.world.item.BalmItemRegistrar;
import net.blay09.mods.balm.world.item.DeferredItem;
import net.minecraft.util.Unit;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.Item;

import java.util.LinkedList;
import java.util.List;
import java.util.function.Function;

public class RDFoodItems {

    public static final List<DeferredItem> FOOD_ITEMS = new LinkedList<>();

    // 食物
    public static DeferredItem ALL_MEAT_FEAST;
    public static DeferredItem ARCTIC_SWEET_SHRIMP_AND_PEACH_SALAD;
    public static DeferredItem ASSORTED_TEMPURA;
    public static DeferredItem A_LITTLE_SWEET_POISON;
    public static DeferredItem BAKED_CRAB_WITH_CREAM;
    public static DeferredItem BAKED_SWEET_POTATOES;
    public static DeferredItem BAMBOO_SHOOTS_FRIED_MEAT;
    public static DeferredItem BAMBOO_SHOOTS_STEWED_IN_STONE_POT;
    public static DeferredItem BAMBOO_STEAMED_EGG;
    public static DeferredItem BAMBOO_TUBE_ROASTED_DRUNKEN_SHRIMP;
    public static DeferredItem BAMBOO_TUBE_STEAMED_PORK;
    public static DeferredItem BEAR_PAW;
    public static DeferredItem BEEF_HOT_POT;
    public static DeferredItem BEEF_RICE;
    public static DeferredItem BEEF_WELLINGTON;
    public static DeferredItem BEETLE_STEAMED_CAKE;
    public static DeferredItem BISCAY_BISCUITS;
    public static DeferredItem BOILED_FISH;
    public static DeferredItem BRAISED_EEL;
    public static DeferredItem BRAISED_PORK_WITH_PEACH;
    public static DeferredItem BURNT_PUDDING;
    public static DeferredItem BUTTER_STEAK;
    public static DeferredItem CANDIED_CHESTNUTS;
    public static DeferredItem CANDIED_SWEET_POTATO;
    public static DeferredItem CATS_PLAYING_IN_WATER;
    public static DeferredItem CAT_FOOD;
    public static DeferredItem CAT_KULULI;
    public static DeferredItem CAT_PIZZA;
    public static DeferredItem CHEESE_EGG;
    public static DeferredItem COLD_DISH_CARVING;
    public static DeferredItem COLD_TOFU;
    public static DeferredItem COLORFUL_JADE_FRIED_BUNS;
    public static DeferredItem COOKING_TOFU;
    public static DeferredItem CREAM_STEW;
    public static DeferredItem CRISP_CYCLONE;
    public static DeferredItem DARK_CUISINE;
    public static DeferredItem DEEP_FRIED_CICADA_SHELLS;
    public static DeferredItem DEPRESSED_CHEESE_STICKS;
    public static DeferredItem DEW_BOILED_EGGS;
    public static DeferredItem DORAYAKI;
    public static DeferredItem DUMPLING;
    public static DeferredItem EEL_EGG_DONBURI;
    public static DeferredItem EGGS_BENEDICT;
    public static DeferredItem ENERGY_STRING;
    public static DeferredItem FAILING_SAKURA_SNOW;
    public static DeferredItem FANTASY_IS_ALL_THE_RAGE;
    public static DeferredItem FISH_LEAPS_OVER_DRAGON_GATE;
    public static DeferredItem FLOWERS_BIRDS_WIND_AND_MOON;
    public static DeferredItem FLOWING_WATER_NOODLES;
    public static DeferredItem FRIED_HAGFISH;
    public static DeferredItem FRIED_PORK_CUTLET;
    public static DeferredItem FRIED_PORK_SHREDS;
    public static DeferredItem FRIED_SHRIMP_TEMPURA;
    public static DeferredItem FRIED_TOFU;
    public static DeferredItem FRIED_TOMATO_STRIPS;
    public static DeferredItem FRIGHT_ADVENTURE;
    public static DeferredItem GAME_SOUP;
    public static DeferredItem GENSOKYO_BUDDHA_JUMPS_OVER_THE_WALL;
    public static DeferredItem GENSOKYO_STAR_LOTUS_SHIP;
    public static DeferredItem GIANT_TAMAGOYAKI;
    public static DeferredItem GINKGO_AND_RADISH_PORK_RIB_SOUP;
    public static DeferredItem GLOOMY_FRUIT_PIE;
    public static DeferredItem GLUTINOUS_RICE_BALLS;
    public static DeferredItem GOLDEN_CRISPY_FISH_CAKE;
    public static DeferredItem GRAND_BANQUET;
    public static DeferredItem GREEN_BAMBOO_WELCOMES_SPRING;
    public static DeferredItem GREEN_FAIRY_MUSHROOM;
    public static DeferredItem GRILLED_HAGFISH;
    public static DeferredItem GRILLED_PORK_RICE_BALLS;
    public static DeferredItem HEART_PORRIDGE_GRUEL;
    public static DeferredItem HELL_THRILL_WARNING;
    public static DeferredItem HOLY_WHITE_LOTUS_SEED_CAKE;
    public static DeferredItem HONEY_BBQ_PORK;
    public static DeferredItem HORAI_DAMA_NO_EDA;
    public static DeferredItem HOT_WAFFLES;
    public static DeferredItem HULA_SOUP;
    public static DeferredItem LION_HEAD;
    public static DeferredItem LONGYIN_PEACH;
    public static DeferredItem LOOKING_UP_AT_THE_CEILING_FRUIT_PIE;
    public static DeferredItem LOTUS_FISH_RICE_BOWL;
    public static DeferredItem LUOHAN_VEGETARIAN;
    public static DeferredItem MAD_HATTER_TEA_PARTY;
    public static DeferredItem MAGMA;
    public static DeferredItem MAOYU_LAVA_TOFU;
    public static DeferredItem MAOYU_TRICOLOR_ICE_CREAM;
    public static DeferredItem MAPO_TOFU;
    public static DeferredItem MILKY_MUSHROOM_SOUP;
    public static DeferredItem MOCHI;
    public static DeferredItem MOLECULAR_EGG;
    public static DeferredItem MOONLIGHT_DUMPLINGS;
    public static DeferredItem MOONLIGHT_OVER_LOTUS_POND;
    public static DeferredItem MOON_CAKE;
    public static DeferredItem MOON_LOVERS;
    public static DeferredItem MUSHROOM_GIRLS_DANCE_STEW;
    public static DeferredItem MUSHROOM_MEAT_SLICES;
    public static DeferredItem NIGIRI_SUSHI;
    public static DeferredItem OEDO_BOAT_FESTIVAL;
    public static DeferredItem OKONOMIYAKI;
    public static DeferredItem ONE_HIT_KILL;
    public static DeferredItem ORDINARY_SMALL_CAKE;
    public static DeferredItem PAN_FRIED_MUSHROOM_MEAT_ROLL;
    public static DeferredItem PAN_FRIED_SALMON;
    public static DeferredItem PEACH_BLOSSOM_GLAZE_ROLL;
    public static DeferredItem PEACH_BLOSSOM_SOUP;
    public static DeferredItem PHOENIX;
    public static DeferredItem PICKLED_CUCUMBERS;
    public static DeferredItem PIG_DEER_BUTTERFLY;
    public static DeferredItem PINE_NUT_CAKE;
    public static DeferredItem PIRATE_BACON;
    public static DeferredItem PLUM_TEA_RICE;
    public static DeferredItem POETRY_AND_GINKGO;
    public static DeferredItem POISONOUS_GARDEN;
    public static DeferredItem PORK_AND_TROUT_SMOKED;
    public static DeferredItem PORK_RICE;
    public static DeferredItem POTATO_CROQUETTES;
    public static DeferredItem PSEUDO_JIRITAMA;
    public static DeferredItem PUMPKIN_SHRIMP_CAKE;
    public static DeferredItem RAPUNZEL;
    public static DeferredItem REAL_SEAFOOD_MISO_SOUP;
    public static DeferredItem RED_BEAN_DAIFUKU;
    public static DeferredItem REFRESHING_PUDDING;
    public static DeferredItem REVERSING_THE_WORLD;
    public static DeferredItem RICE_BALL;
    public static DeferredItem RISOTTO;
    public static DeferredItem ROASTED_MUSHROOMS;
    public static DeferredItem SAKURA_PUDDING;
    public static DeferredItem SALMON_TEMPURA;
    public static DeferredItem SASHIMI_PLATTER;
    public static DeferredItem SCARLET_DEVILS_CAKE;
    public static DeferredItem SCONES;
    public static DeferredItem SCREAMING_ODEN;
    public static DeferredItem SEAFOOD_MISO_SOUP;
    public static DeferredItem SEA_URCHIN_SASHIMI;
    public static DeferredItem SEA_URCHIN_SHINGEN_PANCAKE;
    public static DeferredItem SECRET_DRIED_FISH;
    public static DeferredItem SECRET_MUSHROOM_CASSEROLE;
    public static DeferredItem SEVEN_COLORED_YOKAN;
    public static DeferredItem SHIRAGA_SADAMATSU;
    public static DeferredItem SKINNY_HORSE_DUMPLING;
    public static DeferredItem SNOW_WHITE;
    public static DeferredItem STEAMED_EGG_WITH_SEA_URCHIN;
    public static DeferredItem STINKY_TOFU;
    public static DeferredItem STRENGTH_SOUP;
    public static DeferredItem SUPERME_SEAFOOD_NOODLES;
    public static DeferredItem TAICHI_BAGUA_FISH_MAW;
    public static DeferredItem TAKETORIHIME;
    public static DeferredItem TAKOYAKI;
    public static DeferredItem THE_BEAUTY_OF_HAN_PALACE;
    public static DeferredItem THE_DREAM;
    public static DeferredItem THE_MARS;
    public static DeferredItem THE_SOURCE_OF_LIFE;
    public static DeferredItem TIANSHI_BRAISED_CHESTNUT_MUSHROOMS;
    public static DeferredItem TOFU_MISO;
    public static DeferredItem TOFU_POT;
    public static DeferredItem TONKOTSU_RAMEN;
    public static DeferredItem TOON_PANCAKES;
    public static DeferredItem TWO_HEAVENS_ONE_STYLE;
    public static DeferredItem UDUMBARA_CAKE;
    public static DeferredItem UNCONSCIOUS_MONSTER_MOUSSE;
    public static DeferredItem VEGETABLE_SPECIAL;
    public static DeferredItem WARM_RICE_BALL;
    public static DeferredItem WHITE_PEACH_EIGHT_BRIDGE;
    public static DeferredItem YUNSHAN_COTTON_CANDY;
    public static DeferredItem ZHAJI;

    public static void initialize(BalmItemRegistrar balmItemRegistrar) {
        ALL_MEAT_FEAST = registerFoodItem(balmItemRegistrar, "food/all_meat_feast", foodFactory(), new Item.Properties());
        ARCTIC_SWEET_SHRIMP_AND_PEACH_SALAD = registerFoodItem(balmItemRegistrar, "food/arctic_sweet_shrimp_and_peach_salad", foodFactory(), new Item.Properties());
        ASSORTED_TEMPURA = registerFoodItem(balmItemRegistrar, "food/assorted_tempura", foodFactory(), new Item.Properties());
        A_LITTLE_SWEET_POISON = registerFoodItem(balmItemRegistrar, "food/a_little_sweet_poison", foodFactory(), new Item.Properties());
        BAKED_CRAB_WITH_CREAM = registerFoodItem(balmItemRegistrar, "food/baked_crab_with_cream", foodFactory(), new Item.Properties());
        BAKED_SWEET_POTATOES = registerFoodItem(balmItemRegistrar, "food/baked_sweet_potatoes", foodFactory(), new Item.Properties());
        BAMBOO_SHOOTS_FRIED_MEAT = registerFoodItem(balmItemRegistrar, "food/bamboo_shoots_fried_meat", foodFactory(), new Item.Properties());
        BAMBOO_SHOOTS_STEWED_IN_STONE_POT = registerFoodItem(balmItemRegistrar, "food/bamboo_shoots_stewed_in_stone_pot", foodFactory(), new Item.Properties());
        BAMBOO_STEAMED_EGG = registerFoodItem(balmItemRegistrar, "food/bamboo_steamed_egg", foodFactory(), new Item.Properties());
        BAMBOO_TUBE_ROASTED_DRUNKEN_SHRIMP = registerFoodItem(balmItemRegistrar, "food/bamboo_tube_roasted_drunken_shrimp", foodFactory(), new Item.Properties());
        BAMBOO_TUBE_STEAMED_PORK = registerFoodItem(balmItemRegistrar, "food/bamboo_tube_steamed_pork", foodFactory(), new Item.Properties());
        BEAR_PAW = registerFoodItem(balmItemRegistrar, "food/bear_paw", foodFactory(), new Item.Properties());
        BEEF_HOT_POT = registerFoodItem(balmItemRegistrar, "food/beef_hot_pot", foodFactory(), new Item.Properties());
        BEEF_RICE = registerFoodItem(balmItemRegistrar, "food/beef_rice", foodFactory(), new Item.Properties());
        BEEF_WELLINGTON = registerFoodItem(balmItemRegistrar, "food/beef_wellington", foodFactory(), new Item.Properties());
        BEETLE_STEAMED_CAKE = registerFoodItem(balmItemRegistrar, "food/beetle_steamed_cake", foodFactory(), new Item.Properties());
        BISCAY_BISCUITS = registerFoodItem(balmItemRegistrar, "food/biscay_biscuits", foodFactory(), new Item.Properties());
        BOILED_FISH = registerFoodItem(balmItemRegistrar, "food/boiled_fish", foodFactory(), new Item.Properties());
        BRAISED_EEL = registerFoodItem(balmItemRegistrar, "food/braised_eel", foodFactory(), new Item.Properties());
        BRAISED_PORK_WITH_PEACH = registerFoodItem(balmItemRegistrar, "food/braised_pork_with_peach", foodFactory(), new Item.Properties());
        BURNT_PUDDING = registerFoodItem(balmItemRegistrar, "food/burnt_pudding", foodFactory(), new Item.Properties());
        BUTTER_STEAK = registerFoodItem(balmItemRegistrar, "food/butter_steak", foodFactory(), new Item.Properties());
        CANDIED_CHESTNUTS = registerFoodItem(balmItemRegistrar, "food/candied_chestnuts", foodFactory(), new Item.Properties());
        CANDIED_SWEET_POTATO = registerFoodItem(balmItemRegistrar, "food/candied_sweet_potato", foodFactory(), new Item.Properties());
        CATS_PLAYING_IN_WATER = registerFoodItem(balmItemRegistrar, "food/cats_playing_in_water", foodFactory(), new Item.Properties());
        CAT_FOOD = registerFoodItem(balmItemRegistrar, "food/cat_food", foodFactory(), new Item.Properties());
        CAT_KULULI = registerFoodItem(balmItemRegistrar, "food/cat_kululi", foodFactory(), new Item.Properties());
        CAT_PIZZA = registerFoodItem(balmItemRegistrar, "food/cat_pizza", foodFactory(), new Item.Properties());
        CHEESE_EGG = registerFoodItem(balmItemRegistrar, "food/cheese_egg", foodFactory(), new Item.Properties());
        COLD_DISH_CARVING = registerFoodItem(balmItemRegistrar, "food/cold_dish_carving", foodFactory(), new Item.Properties());
        COLD_TOFU = registerFoodItem(balmItemRegistrar, "food/cold_tofu", foodFactory(), new Item.Properties());
        COLORFUL_JADE_FRIED_BUNS = registerFoodItem(balmItemRegistrar, "food/colorful_jade_fried_buns", foodFactory(), new Item.Properties());
        COOKING_TOFU = registerFoodItem(balmItemRegistrar, "food/cooking_tofu", foodFactory(), new Item.Properties());
        CREAM_STEW = registerFoodItem(balmItemRegistrar, "food/cream_stew", foodFactory(), new Item.Properties());
        CRISP_CYCLONE = registerFoodItem(balmItemRegistrar, "food/crisp_cyclone", foodFactory(), new Item.Properties());
        DARK_CUISINE = registerFoodItem(balmItemRegistrar, "food/dark_cuisine", foodFactory(), new Item.Properties());
        DEEP_FRIED_CICADA_SHELLS = registerFoodItem(balmItemRegistrar, "food/deep_fried_cicada_shells", foodFactory(), new Item.Properties());
        DEPRESSED_CHEESE_STICKS = registerFoodItem(balmItemRegistrar, "food/depressed_cheese_sticks", foodFactory(), new Item.Properties());
        DEW_BOILED_EGGS = registerFoodItem(balmItemRegistrar, "food/dew_boiled_eggs", foodFactory(), new Item.Properties());
        DORAYAKI = registerFoodItem(balmItemRegistrar, "food/dorayaki", foodFactory(), new Item.Properties());
        DUMPLING = registerFoodItem(balmItemRegistrar, "food/dumpling", foodFactory(), new Item.Properties());
        EEL_EGG_DONBURI = registerFoodItem(balmItemRegistrar, "food/eel_egg_donburi", foodFactory(), new Item.Properties());
        EGGS_BENEDICT = registerFoodItem(balmItemRegistrar, "food/eggs_benedict", foodFactory(), new Item.Properties());
        ENERGY_STRING = registerFoodItem(balmItemRegistrar, "food/energy_string", foodFactory(), new Item.Properties());
        FAILING_SAKURA_SNOW = registerFoodItem(balmItemRegistrar, "food/failing_sakura_snow", foodFactory(), new Item.Properties());
        FANTASY_IS_ALL_THE_RAGE = registerFoodItem(balmItemRegistrar, "food/fantasy_is_all_the_rage", foodFactory(), new Item.Properties());
        FISH_LEAPS_OVER_DRAGON_GATE = registerFoodItem(balmItemRegistrar, "food/fish_leaps_over_dragon_gate", foodFactory(), new Item.Properties());
        FLOWERS_BIRDS_WIND_AND_MOON = registerFoodItem(balmItemRegistrar, "food/flowers_birds_wind_and_moon", foodFactory(), new Item.Properties());
        FLOWING_WATER_NOODLES = registerFoodItem(balmItemRegistrar, "food/flowing_water_noodles", foodFactory(), new Item.Properties());
        FRIED_HAGFISH = registerFoodItem(balmItemRegistrar, "food/fried_hagfish", foodFactory(), new Item.Properties());
        FRIED_PORK_CUTLET = registerFoodItem(balmItemRegistrar, "food/fried_pork_cutlet", foodFactory(), new Item.Properties());
        FRIED_PORK_SHREDS = registerFoodItem(balmItemRegistrar, "food/fried_pork_shreds", foodFactory(), new Item.Properties());
        FRIED_SHRIMP_TEMPURA = registerFoodItem(balmItemRegistrar, "food/fried_shrimp_tempura", foodFactory(), new Item.Properties());
        FRIED_TOFU = registerFoodItem(balmItemRegistrar, "food/fried_tofu", foodFactory(), new Item.Properties());
        FRIED_TOMATO_STRIPS = registerFoodItem(balmItemRegistrar, "food/fried_tomato_strips", foodFactory(), new Item.Properties());
        FRIGHT_ADVENTURE = registerFoodItem(balmItemRegistrar, "food/fright_adventure", foodFactory(), new Item.Properties());
        GAME_SOUP = registerFoodItem(balmItemRegistrar, "food/game_soup", foodFactory(), new Item.Properties());
        GENSOKYO_BUDDHA_JUMPS_OVER_THE_WALL = registerFoodItem(balmItemRegistrar, "food/gensokyo_buddha_jumps_over_the_wall", foodFactory(), new Item.Properties());
        GENSOKYO_STAR_LOTUS_SHIP = registerFoodItem(balmItemRegistrar, "food/gensokyo_star_lotus_ship", foodFactory(), new Item.Properties());
        GIANT_TAMAGOYAKI = registerFoodItem(balmItemRegistrar, "food/giant_tamagoyaki", foodFactory(), new Item.Properties());
        GINKGO_AND_RADISH_PORK_RIB_SOUP = registerFoodItem(balmItemRegistrar, "food/ginkgo_and_radish_pork_rib_soup", foodFactory(), new Item.Properties());
        GLOOMY_FRUIT_PIE = registerFoodItem(balmItemRegistrar, "food/gloomy_fruit_pie", foodFactory(), new Item.Properties());
        GLUTINOUS_RICE_BALLS = registerFoodItem(balmItemRegistrar, "food/glutinous_rice_balls", foodFactory(), new Item.Properties());
        GOLDEN_CRISPY_FISH_CAKE = registerFoodItem(balmItemRegistrar, "food/golden_crispy_fish_cake", foodFactory(), new Item.Properties());
        GRAND_BANQUET = registerFoodItem(balmItemRegistrar, "food/grand_banquet", foodFactory(), new Item.Properties());
        GREEN_BAMBOO_WELCOMES_SPRING = registerFoodItem(balmItemRegistrar, "food/green_bamboo_welcomes_spring", foodFactory(), new Item.Properties());
        GREEN_FAIRY_MUSHROOM = registerFoodItem(balmItemRegistrar, "food/green_fairy_mushroom", foodFactory(), new Item.Properties());
        GRILLED_HAGFISH = registerFoodItem(balmItemRegistrar, "food/grilled_hagfish", foodFactory(), new Item.Properties());
        GRILLED_PORK_RICE_BALLS = registerFoodItem(balmItemRegistrar, "food/grilled_pork_rice_balls", foodFactory(), new Item.Properties());
        HEART_PORRIDGE_GRUEL = registerFoodItem(balmItemRegistrar, "food/heart_porridge_gruel", foodFactory(), new Item.Properties());
        HELL_THRILL_WARNING = registerFoodItem(balmItemRegistrar, "food/hell_thrill_warning", foodFactory(), new Item.Properties());
        HOLY_WHITE_LOTUS_SEED_CAKE = registerFoodItem(balmItemRegistrar, "food/holy_white_lotus_seed_cake", foodFactory(), new Item.Properties());
        HONEY_BBQ_PORK = registerFoodItem(balmItemRegistrar, "food/honey_bbq_pork", foodFactory(), new Item.Properties());
        HORAI_DAMA_NO_EDA = registerFoodItem(balmItemRegistrar, "food/horai-dama_no_eda", foodFactory(), new Item.Properties());
        HOT_WAFFLES = registerFoodItem(balmItemRegistrar, "food/hot_waffles", foodFactory(), new Item.Properties());
        HULA_SOUP = registerFoodItem(balmItemRegistrar, "food/hula_soup", foodFactory(), new Item.Properties());
        LION_HEAD = registerFoodItem(balmItemRegistrar, "food/lion_head", foodFactory(), new Item.Properties());
        LONGYIN_PEACH = registerFoodItem(balmItemRegistrar, "food/longyin_peach", foodFactory(), new Item.Properties());
        LOOKING_UP_AT_THE_CEILING_FRUIT_PIE = registerFoodItem(balmItemRegistrar, "food/looking_up_at_the_ceiling_fruit_pie", foodFactory(), new Item.Properties());
        LOTUS_FISH_RICE_BOWL = registerFoodItem(balmItemRegistrar, "food/lotus_fish_rice_bowl", foodFactory(), new Item.Properties());
        LUOHAN_VEGETARIAN = registerFoodItem(balmItemRegistrar, "food/luohan_vegetarian", foodFactory(), new Item.Properties());
        MAD_HATTER_TEA_PARTY = registerFoodItem(balmItemRegistrar, "food/mad_hatter_tea_party", foodFactory(), new Item.Properties());
        MAGMA = registerFoodItem(balmItemRegistrar, "food/magma", foodFactory(), new Item.Properties());
        MAOYU_LAVA_TOFU = registerFoodItem(balmItemRegistrar, "food/maoyu_lava_tofu", foodFactory(), new Item.Properties());
        MAOYU_TRICOLOR_ICE_CREAM = registerFoodItem(balmItemRegistrar, "food/maoyu_tricolor_ice_cream", foodFactory(), new Item.Properties());
        MAPO_TOFU = registerFoodItem(balmItemRegistrar, "food/mapo_tofu", foodFactory(), new Item.Properties());
        MILKY_MUSHROOM_SOUP = registerFoodItem(balmItemRegistrar, "food/milky_mushroom_soup", foodFactory(), new Item.Properties());
        MOCHI = registerFoodItem(balmItemRegistrar, "food/mochi", foodFactory(), new Item.Properties());
        MOLECULAR_EGG = registerFoodItem(balmItemRegistrar, "food/molecular_egg", foodFactory(), new Item.Properties());
        MOONLIGHT_DUMPLINGS = registerFoodItem(balmItemRegistrar, "food/moonlight_dumplings", foodFactory(), new Item.Properties());
        MOONLIGHT_OVER_LOTUS_POND = registerFoodItem(balmItemRegistrar, "food/moonlight_over_lotus_pond", foodFactory(), new Item.Properties());
        MOON_CAKE = registerFoodItem(balmItemRegistrar, "food/moon_cake", foodFactory(), new Item.Properties());
        MOON_LOVERS = registerFoodItem(balmItemRegistrar, "food/moon_lovers", foodFactory(), new Item.Properties());
        MUSHROOM_GIRLS_DANCE_STEW = registerFoodItem(balmItemRegistrar, "food/mushroom_girls_dance_stew", foodFactory(), new Item.Properties());
        MUSHROOM_MEAT_SLICES = registerFoodItem(balmItemRegistrar, "food/mushroom_meat_slices", foodFactory(), new Item.Properties());
        NIGIRI_SUSHI = registerFoodItem(balmItemRegistrar, "food/nigiri_sushi", foodFactory(), new Item.Properties());
        OEDO_BOAT_FESTIVAL = registerFoodItem(balmItemRegistrar, "food/oedo_boat_festival", foodFactory(), new Item.Properties());
        OKONOMIYAKI = registerFoodItem(balmItemRegistrar, "food/okonomiyaki", foodFactory(), new Item.Properties());
        ONE_HIT_KILL = registerFoodItem(balmItemRegistrar, "food/one_hit_kill", foodFactory(), new Item.Properties());
        ORDINARY_SMALL_CAKE = registerFoodItem(balmItemRegistrar, "food/ordinary_small_cake", foodFactory(), new Item.Properties());
        PAN_FRIED_MUSHROOM_MEAT_ROLL = registerFoodItem(balmItemRegistrar, "food/pan_fried_mushroom_meat_roll", foodFactory(), new Item.Properties());
        PAN_FRIED_SALMON = registerFoodItem(balmItemRegistrar, "food/pan_fried_salmon", foodFactory(), new Item.Properties());
        PEACH_BLOSSOM_GLAZE_ROLL = registerFoodItem(balmItemRegistrar, "food/peach_blossom_glaze_roll", foodFactory(), new Item.Properties());
        PEACH_BLOSSOM_SOUP = registerFoodItem(balmItemRegistrar, "food/peach_blossom_soup", foodFactory(), new Item.Properties());
        PHOENIX = registerFoodItem(balmItemRegistrar, "food/phoenix", foodFactory(), new Item.Properties());
        PICKLED_CUCUMBERS = registerFoodItem(balmItemRegistrar, "food/pickled_cucumbers", foodFactory(), new Item.Properties());
        PIG_DEER_BUTTERFLY = registerFoodItem(balmItemRegistrar, "food/pig_deer_butterfly", foodFactory(), new Item.Properties());
        PINE_NUT_CAKE = registerFoodItem(balmItemRegistrar, "food/pine_nut_cake", foodFactory(), new Item.Properties());
        PIRATE_BACON = registerFoodItem(balmItemRegistrar, "food/pirate_bacon", foodFactory(), new Item.Properties());
        PLUM_TEA_RICE = registerFoodItem(balmItemRegistrar, "food/plum_tea_rice", foodFactory(), new Item.Properties());
        POETRY_AND_GINKGO = registerFoodItem(balmItemRegistrar, "food/poetry_and_ginkgo", foodFactory(), new Item.Properties());
        POISONOUS_GARDEN = registerFoodItem(balmItemRegistrar, "food/poisonous_garden", foodFactory(), new Item.Properties());
        PORK_AND_TROUT_SMOKED = registerFoodItem(balmItemRegistrar, "food/pork_and_trout_smoked", foodFactory(), new Item.Properties());
        PORK_RICE = registerFoodItem(balmItemRegistrar, "food/pork_rice", foodFactory(), new Item.Properties());
        POTATO_CROQUETTES = registerFoodItem(balmItemRegistrar, "food/potato_croquettes", foodFactory(), new Item.Properties());
        PSEUDO_JIRITAMA = registerFoodItem(balmItemRegistrar, "food/pseudo_jiritama", foodFactory(), new Item.Properties());
        PUMPKIN_SHRIMP_CAKE = registerFoodItem(balmItemRegistrar, "food/pumpkin_shrimp_cake", foodFactory(), new Item.Properties());
        RAPUNZEL = registerFoodItem(balmItemRegistrar, "food/rapunzel", foodFactory(), new Item.Properties());
        REAL_SEAFOOD_MISO_SOUP = registerFoodItem(balmItemRegistrar, "food/real_seafood_miso_soup", foodFactory(), new Item.Properties());
        RED_BEAN_DAIFUKU = registerFoodItem(balmItemRegistrar, "food/red_bean_daifuku", foodFactory(), new Item.Properties());
        REFRESHING_PUDDING = registerFoodItem(balmItemRegistrar, "food/refreshing_pudding", foodFactory(), new Item.Properties());
        REVERSING_THE_WORLD = registerFoodItem(balmItemRegistrar, "food/reversing_the_world", foodFactory(), new Item.Properties());
        RICE_BALL = registerFoodItem(balmItemRegistrar, "food/rice_ball", foodFactory(), new Item.Properties());
        RISOTTO = registerFoodItem(balmItemRegistrar, "food/risotto", foodFactory(), new Item.Properties());
        ROASTED_MUSHROOMS = registerFoodItem(balmItemRegistrar, "food/roasted_mushrooms", foodFactory(), new Item.Properties());
        SAKURA_PUDDING = registerFoodItem(balmItemRegistrar, "food/sakura_pudding", foodFactory(), new Item.Properties());
        SALMON_TEMPURA = registerFoodItem(balmItemRegistrar, "food/salmon_tempura", foodFactory(), new Item.Properties());
        SASHIMI_PLATTER = registerFoodItem(balmItemRegistrar, "food/sashimi_platter", foodFactory(), new Item.Properties());
        SCARLET_DEVILS_CAKE = registerFoodItem(balmItemRegistrar, "food/scarlet_devils_cake", foodFactory(), new Item.Properties());
        SCONES = registerFoodItem(balmItemRegistrar, "food/scones", foodFactory(), new Item.Properties());
        SCREAMING_ODEN = registerFoodItem(balmItemRegistrar, "food/screaming_oden", foodFactory(), new Item.Properties());
        SEAFOOD_MISO_SOUP = registerFoodItem(balmItemRegistrar, "food/seafood_miso_soup", foodFactory(), new Item.Properties());
        SEA_URCHIN_SASHIMI = registerFoodItem(balmItemRegistrar, "food/sea_urchin_sashimi", foodFactory(), new Item.Properties());
        SEA_URCHIN_SHINGEN_PANCAKE = registerFoodItem(balmItemRegistrar, "food/sea_urchin_shingen_pancake", foodFactory(), new Item.Properties());
        SECRET_DRIED_FISH = registerFoodItem(balmItemRegistrar, "food/secret_dried_fish", foodFactory(), new Item.Properties());
        SECRET_MUSHROOM_CASSEROLE = registerFoodItem(balmItemRegistrar, "food/secret_mushroom_casserole", foodFactory(), new Item.Properties());
        SEVEN_COLORED_YOKAN = registerFoodItem(balmItemRegistrar, "food/seven_colored_yokan", foodFactory(), new Item.Properties());
        SHIRAGA_SADAMATSU = registerFoodItem(balmItemRegistrar, "food/shiraga_sadamatsu", foodFactory(), new Item.Properties());
        SKINNY_HORSE_DUMPLING = registerFoodItem(balmItemRegistrar, "food/skinny_horse_dumpling", foodFactory(), new Item.Properties());
        SNOW_WHITE = registerFoodItem(balmItemRegistrar, "food/snow_white", foodFactory(), new Item.Properties());
        STEAMED_EGG_WITH_SEA_URCHIN = registerFoodItem(balmItemRegistrar, "food/steamed_egg_with_sea_urchin", foodFactory(), new Item.Properties());
        STINKY_TOFU = registerFoodItem(balmItemRegistrar, "food/stinky_tofu", foodFactory(), new Item.Properties());
        STRENGTH_SOUP = registerFoodItem(balmItemRegistrar, "food/strength_soup", foodFactory(), new Item.Properties());
        SUPERME_SEAFOOD_NOODLES = registerFoodItem(balmItemRegistrar, "food/superme_seafood_noodles", foodFactory(), new Item.Properties());
        TAICHI_BAGUA_FISH_MAW = registerFoodItem(balmItemRegistrar, "food/taichi_bagua_fish_maw", foodFactory(), new Item.Properties());
        TAKETORIHIME = registerFoodItem(balmItemRegistrar, "food/taketorihime", foodFactory(), new Item.Properties());
        TAKOYAKI = registerFoodItem(balmItemRegistrar, "food/takoyaki", foodFactory(), new Item.Properties());
        THE_BEAUTY_OF_HAN_PALACE = registerFoodItem(balmItemRegistrar, "food/the_beauty_of_han_palace", foodFactory(), new Item.Properties());
        THE_DREAM = registerFoodItem(balmItemRegistrar, "food/the_dream", foodFactory(), new Item.Properties());
        THE_MARS = registerFoodItem(balmItemRegistrar, "food/the_mars", foodFactory(), new Item.Properties());
        THE_SOURCE_OF_LIFE = registerFoodItem(balmItemRegistrar, "food/the_source_of_life", foodFactory(), new Item.Properties());
        TIANSHI_BRAISED_CHESTNUT_MUSHROOMS = registerFoodItem(balmItemRegistrar, "food/tianshi_braised_chestnut_mushrooms", foodFactory(), new Item.Properties());
        TOFU_MISO = registerFoodItem(balmItemRegistrar, "food/tofu_miso", foodFactory(), new Item.Properties());
        TOFU_POT = registerFoodItem(balmItemRegistrar, "food/tofu_pot", foodFactory(), new Item.Properties());
        TONKOTSU_RAMEN = registerFoodItem(balmItemRegistrar, "food/tonkotsu_ramen", foodFactory(), new Item.Properties());
        TOON_PANCAKES = registerFoodItem(balmItemRegistrar, "food/toon_pancakes", foodFactory(), new Item.Properties());
        TWO_HEAVENS_ONE_STYLE = registerFoodItem(balmItemRegistrar, "food/two_heavens_one_style", foodFactory(), new Item.Properties());
        UDUMBARA_CAKE = registerFoodItem(balmItemRegistrar, "food/udumbara_cake", foodFactory(), new Item.Properties());
        UNCONSCIOUS_MONSTER_MOUSSE = registerFoodItem(balmItemRegistrar, "food/unconscious_monster_mousse", foodFactory(), new Item.Properties());
        VEGETABLE_SPECIAL = registerFoodItem(balmItemRegistrar, "food/vegetable_special", foodFactory(), new Item.Properties());
        WARM_RICE_BALL = registerFoodItem(balmItemRegistrar, "food/warm_rice_ball", foodFactory(), new Item.Properties());
        WHITE_PEACH_EIGHT_BRIDGE = registerFoodItem(balmItemRegistrar, "food/white_peach_eight_bridge", foodFactory(), new Item.Properties());
        YUNSHAN_COTTON_CANDY = registerFoodItem(balmItemRegistrar, "food/yunshan_cotton_candy", foodFactory(), new Item.Properties());
        ZHAJI = registerFoodItem(balmItemRegistrar, "food/zhaji", foodFactory(), new Item.Properties());

    }

    public static DeferredItem registerFoodItem(BalmItemRegistrar balmItemRegistrar, String name, Function<Item.Properties, Item> factory, Item.Properties settings) {
        DeferredItem item = RDItems.registerSimpleItem(balmItemRegistrar, name, factory, settings);
        FOOD_ITEMS.add(item);
        return item;
    }

    public static Function<Item.Properties, Item> foodFactory() {
        return props -> new Item(props.component(RDDataComponents.FOOD_ITEM_TYPE.value(), Unit.INSTANCE)
                .food(new FoodProperties.Builder().nutrition(2).saturationModifier(2).build()));
    }


}
