name: paper
description: $description
version: '${version}'

main: cc.thonly.reverie_dreams.paper.ReverieDreamsPlugin
bootstrapper: cc.thonly.paper.ReverieDreamsBootstrap
loader: cc.thonly.paper.ReverieDreamsLoader
api-version: '26.1.2'
load: POSTWORLD

authors: [稀神灵梦]
website: https://github.com/SAGUMEDREAM/ReverieDreams
